spring:
  application:
    name: webflux-kotlin
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:15432/${DB_NAME:testdb}
    username: ${DB_USERNAME:userpgd}
    password: ${DB_PASSWORD:userpgd}